kubernetesClusterDomain: cluster.local
storeFront:
  nodeSelector:
    kubernetes.io/os: linux
  ports:
  - port: 80
    targetPort: 8080
  replicas: 1
  storeFront:
    image:
      repository: acronlinestoredevuksouth001.azurecr.io/store-front
      tag: 1.0.0
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: 1m
        memory: 200Mi
  type: LoadBalancer
